version: '3.8'

services:
    node:
        build: ./node
        ports: 
            - 8888:8888
        volumes: 
            - ./node/project:/project
    nginx:
        build: ./nginx
        ports: 
            - 80:80
        depends_on:
            - node